// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PDFArchiveApp.Standard.Model.v2;
using System;

namespace PDFArchiveApp.Standard.Model.v2.Migrations
{
    [DbContext(typeof(PdfEntryContext))]
    [Migration("20180304201157_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("PDFArchiveApp.Standard.Model.PdfEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("Created");

                b.Property<Guid>("EntryId");

                b.Property<string>("Filename");

                b.Property<string>("SourcePath");

                b.HasKey("Id");

                b.ToTable("PdfEntrys");
            });

            modelBuilder.Entity("PDFArchiveApp.Standard.Model.PdfTag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.Property<int?>("PdfEntryId");

                b.HasKey("Id");

                b.HasIndex("PdfEntryId");

                b.ToTable("Tags");
            });

            modelBuilder.Entity("PDFArchiveApp.Standard.Model.PdfTag", b =>
            {
                b.HasOne("PDFArchiveApp.Standard.Model.PdfEntry")
                    .WithMany("Tags")
                    .HasForeignKey("PdfEntryId");
            });
#pragma warning restore 612, 618
        }
    }
}
